name: Release

on:
  push:
    branches:
      - "main"

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  publish:
    name: Publish NPM package
    runs-on: ubuntu-latest
    # Avoid publishing in forks
    if: github.repository == 'testing-library/eslint-plugin-testing-library'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build and test
        run: yarn build
      - name: Test
        run: yarn test

      - name: Release new version
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
